[package]
name = "notera"
version = "0.1.0-alpha.2"
edition = "2024"
authors = ["Harrison Knight <hijknight@icloud.com>"]
description = "notera is an open source minimal note taking tool"
license = "MIT"
readme = "README.md"
repository = "https://github.com/hijknight/notera.git"

[[bin]]
name = "notera"
path = "src/main.rs"


[dependencies]
clap = { version = "4.4", features = ["derive"]}
chrono = "0.4"
serde = {  version = "1.0.218", features = ["derive"] }
toml = "0.8"
dirs = "6.0"
rusqlite = { version = "0.34", features = ["bundled"] }
