[package]
name = "note-taker"
version = "0.1.0"
edition = "2021"
authors = ["Harrison Knight", "hijknight@icloud.com"]
description = "Note taker is an open source minimal note taking tool built in 30 minutes"
license = "MIT"


[dependencies]
chrono = "0.4.39"
crossterm = "0.28.1"
serde = {  version = "1.0.218", features = ["derive"] }
serde_json = "1.0.139"
tui = "0.19.0"
